### ISSUE TITLE
Solicitudes de caracteristicas

### ISSUE THREAD

**Issue by andresgarcia0313** [MauricioRobayo/colombian-holidays#409]
Buen día apreciado Mauricio

Felicidades por tan buen paquete
De acuerdo a tu solicitud te doy estás recomendaciones

1. Dejar en el readme Como se Regala un⭐️a este proyecto, no encontré forma en el mismo.
2. Crear una funcion de con parametro el parametro fecha y retorno booleano respondiendo si la fecha consultada es booleano.
3. Crear una función con dos parametros de entrada que sería fecha inicio y fecha fin y retorne la cantidad de días festivos, cantidad de sabados, cantidad de domingos, lista de días festivos.
4. Agregar en el listado que retorna colombianHolidays() una columna en formato estandar de fechas js para evitar demoras en conversión cuando se utilizan miles de fechas.
5. Permitir consultar fechas de años anteriores a que colocaran los lunes como festivos (no lo he intentado consultar en el código en este momento pero lo haré)
6. En mi caso particular muchas veces valido el rendimiento de conversiones o trata de datos midiendolo en segundos con metodos asincronicos llamados por ciclos repetitivos.
7. Y por que no, permite que se consute si es festivo con el parametro país, este paquete se puede volver el más usado en el planeta en los software como recursos humanos, ai, cms, calendarios 

De antemano es de decir que está bien hecho este paquete y muestra la calidad de tu trabajo, espero que mis ideas dejen este paquete más pro de lo que ya es, un saludo y muchas muchas gracias por tu contribución a todos les ahorras un tiempo valioso.

Feliz Día

**Comment by MauricioRobayo** [comment]
Hola @andresgarcia0313 !

Antes que nada, muchas gracias por abrir el issue y perdón por la demora en responder.

> 1. Dejar en el readme Como se Regala unstara este proyecto, no encontré forma en el mismo.

Gracias, es cierto, buen punto.

> 2. Crear una funcion de con parametro el parametro fecha y retorno booleano respondiendo si la fecha consultada es booleano.

Muy buena idea, gracias, estoy de acuerdo en incluir esta función.

> 3. Crear una función con dos parametros de entrada que sería fecha inicio y fecha fin y retorne la cantidad de días festivos, cantidad de sabados, cantidad de domingos, lista de días festivos.

Esto puede ser muy útil, buena sugerencia.

> 4. Agregar en el listado que retorna colombianHolidays() una columna en formato estandar de fechas js para evitar demoras en conversión cuando se utilizan miles de fechas.

Excelente.

> 5. Permitir consultar fechas de años anteriores a que colocaran los lunes como festivos (no lo he intentado consultar en el código en este momento pero lo haré)

Sí, genial, no debe ser difícil de implementar el agregar soporte a esto.

> 6. En mi caso particular muchas veces valido el rendimiento de conversiones o trata de datos midiendolo en segundos con metodos asincronicos llamados por ciclos repetitivos.

:+1: (entiendo que es más un comentario que una sugerencia)

> 7. Y por que no, permite que se consute si es festivo con el parametro país, este paquete se puede volver el más usado en el planeta en los software como recursos humanos, ai, cms, calendarios

Si no recuerdo mal esa librería a existe, espérame busco, ya vuelvo... acá está: https://github.com/commenthol/date-holidays.

Con respecto a las dos funciones adicionales: `isHoliday(date: Date)` y `holidaysWithin(startDate: Date, endDate: Date)` (es sólo una sugerencia para los nombres de estar funciones) , tengo algo de sentimientos encontrados con incluirlas.

Me gusta que la librería sea sencilla y cumpla una función, sin sobrecargarla, pero estoy de acuerdo que pueden ser funciones comúnmente usadas. Dicho esto, si las incluimos, me inclinaría por hacerlas exports independientes, de tal forma que no afecten el tamaño del bundle si sólo se incluye la función principal (`import isHoliday from "colombian-holidays/isHoliday";`)

Yo trabajaría dando la siguiente prioridad: 

- [x] 5. Permitir consulta de fechas anteriores a 1984.
- [x] 4. Agregar columna con fechas en formato Date de JS. La fecha debe corresponder al inicio del correspondiente día en Colombia. Por ejemplo, `2022-12-08` sería '2022-12-08T00:00:00.000-05:00'. Esto puede ser truculento deberíamos incluir buenos tests de respaldo.
- [x] 2. `isHoliday(date: Date): boolean`
- [x] 3. `holidaysWithin(startDate: Date, endDate: Date): {holidaysCount: number, holidaysList: ColombianHoliday[], /* ... */}`
- [x] 1. Actualizar Readme.

Sería genial si tu pudieras trabajar en esos cambios ya que son tus ideas.

Avísame si tienes el tiempo de trabajar en esto, no hay afán. Si no tienes el tiempo no pasa nada, yo puedo hacerlo, me demoraré un poco pero saldrá :+1: 

Una vez más, ¡muchas gracias por tu aporte!
