### ISSUE TITLE
Deploy error in Google Cloud Platform

### ISSUE THREAD

**Issue by Josnic** [MauricioRobayo/colombian-holidays#66]
Hi. first, your work is awesome.

I have a problem with a deploy in Google Cloud Platform:

![image](https://user-images.githubusercontent.com/13033658/113956513-322b4900-97e3-11eb-8e33-63ffb1aede0c.png)

I do my deploy with runtime Node10 and Node12. The error is the same. 

Thanks you.

**Comment by MauricioRobayo** [comment]
Hi @Josnic , thanks for reporting the issue.

Seems like the git command fails when trying to add hooksPath on a non git directory, that's only for development, so we could safely ignore those failing scripts in that case.

I've pushed a fix, could you please verify that it solves the issue.

**Comment by Josnic** [comment]
Hi @MauricioRobayo 

I have updated the version and it works perfectly again. Thanks you so much.
